### ISSUE TITLE
Problem in Preprocessing 

### ISSUE THREAD

**Issue by TuhinPatra633** [sangwu99/Simplot#1]
I found that the preprocess.py file is crashing after running 10%. I have updated the code and could reach maximum upto 50%. Can you make it 100% anf fix the issue.

**Comment by sangwu99** [comment]
Sorry for the late reply. In our environment, 100% preprocessing is possible. Please ensure that you have correctly specified the environment and the location of the data. If preprocessing still does not proceed properly, please check where the issue is occurring and let us know; we will provide a response accordingly. Thank you for your interest in our research.
